config/routes.rb
Rails.application.routes.draw do

  resources :tools

  resources :users, only: [:new, :index, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'users#index'

  namespace :admin do
    resources :categories
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tools
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :user
  belongs_to :category  
  # this prevents you from submitting a form with a missing name attribute
  def formatted_price
    price / 100.0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
  has_many :tools

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/404' unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :most_recent_tool,
                :current_user

  def most_recent_tool
    if current_user
      @tools = current_user.tools
      session[:most_recent_tool_id] = @tools.order(:created_at).last
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:errors] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  def index
    @tools = current_user.tools
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    # or Tool.destroy(params[:id]) works just as well
    redirect_to tools_path
  end

  def create
    # generate a new tool
    # add the attributes to that tool - down in tool_params
    @tool = Tool.new(tool_params)
    # try to save that tool
    if @tool.save
      current_user.tools << @tool
      # save method handles validations
      # if the tool saves to the database we will send the user to view that tool
      flash[:notice] = "You just created a tool!"
      redirect_to tool_path(@tool.id)
      # redirect_to @tool does same thing in much more magical way
    else
      # if it doesnt save we will render the new view
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to @tool
    else
      edit_tool_path(@tool)
    end
  end


  private

  def tool_params
    params.require(:tool).permit(:name, :quantity, :price)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
      user = User.create(user_params)
      session[:user_id] = user.id
      redirect_to user
  end

  def show
    current_user
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if most_recent_tool %>
  <p>
    <strong>Newest tool:</strong> <%= most_recent_tool.name %>
    </p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for @tool do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.submit %>


<% end %>

<!-- form_for is form helper that takes two arguments -->
<!-- optional argument for submit, but defaults to create tool in this case -->

app/views/tools/edit.html.erb
<%= render "form" %>

app/views/tools/index.html.erb
<% @tools.each do |tool| %>
 <h3><%= tool.name %> - <%= tool.quantity %> <%= link_to "Link to View #{tool.name}", tool_path(tool.id) %> </h3>
<% end %>
<%= link_to("Create a Tool", new_tool_path) %>

<!-- link_to is link helper, which takes two arguments -->

app/views/tools/new.html.erb
<%= render "form" %>

app/views/tools/show.html.erb
<div class="tool_info">
<%= flash[:notice] %>
<h1><%= @tool.name %> - <%= @tool.quantity %></h1>
<h3><%= @tool.formatted_price %></h3>
<% if @tool.category %>
<h3> <%= @tool.category.name %> </h3>
<% end %>
<%= link_to "Destroy #{@tool.name}", tool_path(@tool.id), method: "delete" %>
<%= link_to "Update #{@tool.name}", edit_tool_path(@tool.id) %>
<%= link_to("my tools", tools_path) %>


</div>

app/views/users/index.html.erb
<h1>Need to Register?</h1>
<h2><%= link_to("register", new_user_path) %></h2>

<h1>Already registered? Login</h1>
<h2><%= link_to("login", login_path) %></h2>

app/views/users/new.html.erb
<h1>New User Registration</h1>

  <%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<%= "Welcome, #{@current_user.username}" %>
<%= link_to("logout", logout_path, method: :delete) %>
<%= link_to("my tools", tools_path) %>